<?php

/**
 * @file
 * A module for browsing mail archives provided by the mailarchive module.
 * Copyright (c) 2007.
 *   Jeremy Andrews <jeremy@kerneltrap.org>.  All rights reserved.
 */

/**
 * Drupal _perm hook.  Defines permissions utilized by this module and its
 * API.
 *
 * @return
 *  An array of permissions.
 */
function mailarchive_view_perm() {
  return array('access mailing list archives');
}

/**
 * Drupal _menu hook. 
 *
 * @param $may_cache
 *  A boolean that's either TRUE or FALSE
 *
 * @return
 *  An array of menu items.
 */
function mailarchive_view_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array('path' => 'mailarchive',
      'title' => t('Mailing list archives'),
      'access' => user_access('access mailing list archives'),
      'callback' => 'mailarchive_view_page');
  }
  else {
    if ($sid = _mailarchive_sid(arg(1))) {
      $mailarchive = arg(1);
      $year = (int)arg(2);
      $month = (int)arg(3);
      $day = (int)arg(4);
      $mid = arg(5);
      if ((strlen(arg(2)) != 4) && (arg(3) != 'search')) {
        // Could be an old-style URL, let's check.
        $date = db_fetch_object(db_query('SELECT year, month, day FROM {mailarchive_messages} WHERE sid = %d AND mid = %d', $sid, arg(2)));
        if ($date->year && $date->month && $date->day) {
          // Yes, it's an old-style URL, redirect to correct URL.
          drupal_goto("mailarchive/$mailarchive/$date->year/$date->month/$date->day/". arg(2));
        }
      }
      $items[] = array('path' => "mailarchive/$mailarchive",
        'type' => MENU_SUGGESTED_ITEM,
        'callback' => 'mailarchive_view_mailarchive_overview',
        'callback arguments' => array($mailarchive, $year, $month, $day),
        'access' => user_access('access mailing list archives')
      );
      $items[] = array('path' => "mailarchive/$mailarchive/$year/$month/$day",
        'type' => MENU_SUGGESTED_ITEM,
        'callback' => 'mailarchive_view_mailarchive',
        'callback arguments' => array($mailarchive, $year, $month, $day, $mid),
        'access' => user_access('access mailing list archives')
      );
      if (is_numeric(arg(2))) {
        if (arg(3) == 'search') {
          $mid = (int)arg(2);
          switch (arg(4)) {
            case 'subject':
              $items[] = array(
                'path' => "mailarchive/$mailarchive/$mid/search/subject",
                'type' => MENU_CALLBACK,
                'callback' => 'mailarchive_view_search_subject',
                'callback arguments' => array($sid, $mid),
                'access' => user_access('access mailing list archives')
              );
              break;
            case 'from-name':
              $items[] = array(
                'path' => "mailarchive/$mailarchive/$mid/search/from-name",
                'type' => MENU_CALLBACK,
                'callback' => 'mailarchive_view_search_from_name',
                'callback arguments' => array($sid, $mid),
                'access' => user_access('access mailing list archives')
              );
              break;
            case 'from-address':
              $items[] = array(
                'path' => "mailarchive/$mailarchive/$mid/search/from-address",
                'type' => MENU_CALLBACK,
                'callback' => 'mailarchive_view_search_from_address',
                'callback arguments' => array($sid, $mid),
                'access' => user_access('access mailing list archives')
              );
              break;
          }
        }
      }
    }
  }

  return $items;
}

/**
 * Drupal nodeapi _view hook. 
 */
function mailarchive_view(&$node, $teaser = FALSE, $page = FALSE) {
  $node = node_prepare($node, $teaser);
  $node->content['overview'] = array(
    '#value' => mailarchive_view_mailarchive_overview($node->urlname),
    '#weight' => 1,
  );
  return $node;
}

/**
 * Display the mailarchive user overview page, listing all mailing list
 * archives.
 */
function mailarchive_view_page($tid = 0) {
  if (module_exists('taxonomy')) {
    $header = array(t('Mailing list archive'), t('Messages'), t('Last message'));
    if ($tid) {
      _mailarchive_view_set_breadcrumb(1);
      $name = db_result(db_query('SELECT name FROM term_data WHERE tid = %d', $tid));
      drupal_set_title(t('!name mailing list archives', array('!name' => $name)));
      $rows = mailarchive_view_display_subscriptions($tid);
    }
    $tree = taxonomy_get_tree(_mailarchive_get_vid(), $tid);
    if ($tree) {
      foreach ($tree as $term) {
        if (in_array($term->tid, variable_get('mailarchive_categories', array()))) {
          $description = '<div style="margin-left: '. ($term->depth * 30) ."px;\">\n";
          $description .= ' <div class="name">'. l($term->name, "mailarchive/$term->tid") ."</div>\n";
          if ($term->description) {
            $description .= ' <div class="description">'. filter_xss_admin($term->description) ."</div>\n";
          }
          $description .= "</div>\n";
          $rows[] = array(array('data' => $description, 'class' => 'container', 'colspan' => 3));
          $rows = array_merge($rows, mailarchive_view_display_subscriptions($term->tid, $term->depth + 1));
        }
      }
    }
    // We'll use forum's css for now.
    $output = '<div id="forum">';
    $output .= theme('table', $header, $rows);
    $output .= '</div>';
    return $output;
  }
  else {
    drupal_set_message(t('The mailarchive module requires that the taxonomy module be enabled and properly configured.'), 'error');
    return '';
  }
}

/**
 * Display mailing list details for user overview page.
 * TODO: Cleanup this function.
 * TODO: Improve performance -- this page is way too slow to load.
 */
function mailarchive_view_display_subscriptions($tid, $depth = 0) {
  $result = db_query('SELECT s.sid, s.urlname, n.nid, n.title, s.message_count, s.last_message, t.tid FROM {term_node} t INNER JOIN {node} n ON t.nid = n.nid INNER JOIN {mailarchive_subscriptions} s ON n.nid = s.nid WHERE t.tid = %d ORDER BY last_message DESC', $tid);
  while ($subscription = db_fetch_object($result)) {
    if ($subscription->message_count) {
      $last_message = _mailarchive_time_since($subscription->last_message) .' ago';
      $year = date('Y', $subscription->last_message);
      $month = date('n', $subscription->last_message);
      $day = date('j', $subscription->last_message);
/*
      $mid = db_result(db_query('SELECT MAX(mid) FROM {mailarchive_messages} WHERE sid = %d GROUP BY sid', $subscription->sid));
      $message = db_fetch_object(db_query('SELECT mid, subject, received FROM {mailarchive_messages} WHERE sid = %d AND mid = %d', $subscription->sid, $mid));
      $from = db_fetch_object(db_query("SELECT aid, name, mailbox, host FROM {mailarchive_messages_addresses WHERE sid = %d AND mid = %d AND address_type = 'from'", $subscription->sid, $mid));
      if ($from->name) {
        $source = $from->name;
      }
      else {
        $source = "$from->mailbox@...";
      }
      if (strlen($source) > 64) {
        $source = substr($source, 0, 61) .'...';
      }
      $last_message .= ' <div class="description">'. t('From: '). filter_xss_admin($source);
      if ($message->subject) {
        if (strlen($message->subject) > 64) {
          $message->subject = substr($message->subject, 0, 61) .'...';
        }
        $last_message .= '<br /> '. t('Subject: '). filter_xss_admin(l($message->subject, "mailarchive/$subscription->urlname/$message->mid"));
      }
      $last_message .= '<br /> '. t('Date: '). format_date($message->received, 'custom', 'M j, g:i a Y');
      $last_message .= " </div>\n";
*/
    }
    else {
      $last_message = t('none');
    }
    $description = '<div style="margin-left: '. (($depth) * 30) ."px;\">\n";
    if ($year) {
      $description .= ' <div class="name">'. l($subscription->title, "mailarchive/$subscription->urlname/$year/$month/$day") ."</div>\n";
    }
    else {
      $description .= ' <div class="name">'. l($subscription->title, "mailarchive/$subscription->urlname") ."</div>\n";
    }
    $node = node_load($subscription->nid);
    if ($node->body) {
      $description .= ' <div class="description">'. filter_xss_admin($node->body) ."</div>\n";
    }
    $description .= "</div>\n";

    $rows[] = array(
      array('data' => $description, 'class' => 'mailarchive'),
      array('data' => $subscription->message_count),
      array('data' => $last_message)
    );
  }
  return $rows ? $rows : array();
}

function mailarchive_view_mailarchive_overview($mailarchive, $year = NULL, $month = NULL) {
  $sid = _mailarchive_sid($mailarchive);
  if ($year == NULL) {
    _mailarchive_view_set_breadcrumb($sid);
    drupal_set_title(t("!list mailing list", array('!list' => $mailarchive)));
    $header = array(t('Year'), t('Messages'));
    $result = db_query('SELECT COUNT(year) AS messages, year FROM {mailarchive_messages} WHERE sid = %d GROUP BY year DESC', $sid);
    while ($list = db_fetch_object($result)) {
      $row = array();
      $row[] = l($list->year, "mailarchive/$mailarchive/$list->year");
      $row[] = l($list->messages, "mailarchive/$mailarchive/$list->year");
      $rows[] = $row;
    }
  }
  else if ($month == NULL) {
    _mailarchive_view_set_breadcrumb($sid, 1);
    drupal_set_title(t("!list mailing list", array('!list' => $mailarchive, '!year' => $year)));
    $header = array(t('Month'), t('Messages'));
    $result = db_query('SELECT COUNT(month) AS messages, month FROM {mailarchive_messages} WHERE sid = %d AND year = %d GROUP BY month DESC', $sid, $year);
    while ($list = db_fetch_object($result)) {
      $row = array();
      $row[] = l(mailarchive_view_format_month($list->month) ." $year", "mailarchive/$mailarchive/$year/$list->month");
      $row[] = l($list->messages, "mailarchive/$mailarchive/$year/$list->month");
      $rows[] = $row;
    }
  }
  else if ($day == NULL) {
    _mailarchive_view_set_breadcrumb($sid, 1, $year);
    drupal_set_title(t("!list mailing list", array('!list' => $mailarchive, '!year' => $year, '!month' => mailarchive_view_format_month($month))));
    $header = array(t('Day'), t('Messages'));
    $result = db_query('SELECT COUNT(day) AS messages, day FROM {mailarchive_messages} WHERE sid = %d AND year = %d AND month = %d GROUP BY day DESC', $sid, $year, $month);
    while ($list = db_fetch_object($result)) {
      $row = array();
      $row[] = l(mailarchive_view_format_month($month) ." $list->day, $year", "mailarchive/$mailarchive/$year/$month/$list->day");
      $row[] = l($list->messages, "mailarchive/$mailarchive/$year/$month/$list->day");
      $rows[] = $row;
    }
  }
  $output = '<div class="mailarchive">';
  $output .= theme('table', $header, $rows);
  $output .= '</div>';
  return $output;
}

function mailarchive_view_format_month($month) {
  switch ($month) {
    case 1:
      return t('January');
    case 2:
      return t('February');
    case 3:
      return t('March');
    case 4:
      return t('April');
    case 5:
      return t('May');
    case 6:
      return t('June');
    case 7:
      return t('July');
    case 8:
      return t('August');
    case 9:
      return t('September');
    case 10:
      return t('October');
    case 11:
      return t('November');
    case 12:
      return t('December');
    default:
      return t('Unknown');
  }
}

/**
 * Decides if page trying to be viewed is a single message or an archive/list.
 * If single message, pass to theme_mailarchive_view_message.
 * If archive, pass to theme_mailarchive_view_thread.
 */
function mailarchive_view_mailarchive($mailarchive, $year, $month, $day, $messageid = 0) {
  $sid = _mailarchive_sid($mailarchive);
  if ($messageid) {
    // Display only specified message.
    _mailarchive_view_set_breadcrumb($sid, $messageid, $year, $month, $day);
    $output .= theme('mailarchive_view_message', $mailarchive, $messageid);
  }
  else {
    // Display all threads in mailing list.
    _mailarchive_view_set_breadcrumb($sid, 1, $year, $month);
    $output .= theme('mailarchive_view_thread', $mailarchive, $year, $month, $day);
  }
  return $output;
}

/**
 * Displays the contents/messages for the archive specified in $mailarchive
 *
 * @param string $mailarchive - contains the "urlname" of the archive to display
 * @param string $year
 * @param string $month
 * @param string $day
 * @return unknown
 */
function theme_mailarchive_view_thread($mailarchive, $year = NULL, $month = NULL, $day = NULL) {
  $sid = _mailarchive_sid($mailarchive);
  if (!$sid) {
    drupal_set_message(t('Unknown mailing list, %mailarchive.', array('%mailarchive' => $mailarchive)));
    drupal_goto('mailarchive');
  }
  drupal_set_title("$mailarchive mailing list");
  $order = isset($_GET['order']) ? $_GET['order'] : '';
  
  $sql_range = "year = $year AND month = $month AND day = $day";
  $messages_per_page = ((int)$_GET['messages_per_page'] ? (int)$_GET['messages_per_page'] : 25);

  $output = "<div class=\"mailarchive\"><div class=\"message-list\" id=\"message-list-$mailarchive\">\n";

  $header = array(
    array('data' => t('Subject'), 'field' => 'thread_id', 'sort' => 'desc'),
    array('data' => t('From'), 'field' => 'mailfrom'),
    array('data' => t('Date'), 'field' => 'received')
  );
  
  // TODO: Fix this to be threaded and sorted properly.
  // Get list of messages in current group.
  $sql = "SELECT mid, received, year, month, day, subject, mailfrom, thread_id, sub_thread_id FROM {mailarchive_messages} WHERE $sql_range AND sid = $sid";
  $sql .= tablesort_sql($header) .', sub_thread_id DESC';
  $result = pager_query($sql, $messages_per_page, 0, "SELECT COUNT(thread_id) FROM {mailarchive_messages} WHERE $sql_range AND sid = %d", $sid);
  
  $output .= "<div class=\"message-list-thread\" id =\"message-list-$mailarchive\">\n";
  while ($message = db_fetch_object($result)) {
    $row = array();

    // We only indent threads if ordered by subject, otherwise we're not really
    // displaying threads.
    if (!$order || $order == t('Subject')) {
      $message->depth = count(explode('.', $message->sub_thread_id)) -1;
    }

    // Subject row:
    if ($message->subject) {
      if (strlen($message->subject) > 62) {
        $message->subject = substr(htmlspecialchars($message->subject), 0, 60) .'...';
      }
    }
    else {
      $message->subject = t('(No subject)');
    }
    $subject = '<div class="message-list-thread-line" style="margin-left: '. ($message->depth * 15) .'px;">';
    $subject .= ' <span class="message-list-thread-subject">'. l($message->subject, "mailarchive/$mailarchive/$message->year/$message->month/$message->day/$message->mid") .'</span>';
    $subject .= "</div>\n";
    $row[] = $subject;

    // From row:
    $row[] = (strlen($message->mailfrom) > 24 ? substr(htmlspecialchars($message->mailfrom), 0, 20). '...' : htmlspecialchars($message->mailfrom));

    // Date row
    $row[] = format_date($message->received, 'custom', 'M j, g:i a Y');

    $rows[] = $row;
  }

  $output .= theme('table', $header, $rows);
  $output .= theme('pager', NULL, $messages_per_page, 0, NULL);

  $output .= theme('table', array(t('previous day'), t('today'), t('next day')), array(array(mailarchive_view_day_nav($mailarchive, $year, $month, $day, '<'), mailarchive_view_format_month($month) ." $day, $year", mailarchive_view_day_nav($mailarchive, $year, $month, $day, '>'))));

  $output .= "</div></div></div>\n";
  return $output;
}

/**
 * Return the previous or next day with messages, if any.
 */
function mailarchive_view_day_nav($mailarchive, $year, $month, $day, $op) {
  if ($op == '<') {
    $order = 'DESC';
  }
  else {
    $order = 'ASC';
  }
  $sid = _mailarchive_sid($mailarchive);
  // Start with a quick search in the same month.
  $found = db_result(db_query("SELECT day FROM {mailarchive_messages} WHERE sid = %d AND year = %d AND month = %d AND day $op %d GROUP BY day $order LIMIT 1", $sid, $year, $month, $day));
  if (!$found) {
    // Try another quick search
    if ($op == '<') {
      if ($month > 1) {
        $month2 = $month - 1;
        $year2 = $year;
      }
      else {
        $month2 = 12;
        $year2 = $year - 1;
      }
    }
    else {
      if ($month < 12) {
        $month2 = $month + 1;
        $year2 = $year;
      }
      else {
        $month2 = 01;
        $year2 = $year + 1;
      }
    }
    $found = db_result(db_query("SELECT day FROM {mailarchive_messages} WHERE sid = %d AND year = %d AND month = %d AND day $op %d GROUP BY day $order LIMIT 1", $sid, $year2, $month2, $day));
    if (!$found) {
      // Quick searches aren't working, expand our search.
      $found = db_fetch_object(db_query("SELECT year, month, day FROM {mailarchive_messages} WHERE sid = %d AND year = %d AND month $op= %d ORDER BY month $order, day $order LIMIT 1", $sid, $year2, $month2));
      if (!$found->day) {
        // Still nothing, do a full search.
        $found = db_fetch_object(db_query("SELECT year, month, day FROM {mailarchive_messages} WHERE sid = %d AND year $op %d ORDER BY year $order, month $order, day $order LIMIT 1", $sid, $year));
        if ($found) {
          $day = $found->day;
          $month = $found->month;
          $year = $found->year;
        }
        else {
          $day = $month = $year = NULL;
        }
      }
      else {
        $day = $found->day;
        $month = $found->month;
        $year = $found->year;
      }
    }
    else {
      $day = $found;
      $month = $month2;
      $year = $year2;
    }
  }
  else {
    $day = $found;
  }

  if ($day && $month && $year) {
    return l(mailarchive_view_format_month($month) ." $day, $year", "mailarchive/$mailarchive/$year/$month/$day");
  }
  else {
    return t('None');
  }
}

function theme_mailarchive_view_message_nav($mailarchive, $message) {
  $output = "\n<div class=\"message-nav\">";
  $output .= t('Previous message: ');
  $output .= '['. mailarchive_view_message_thread($mailarchive, $message, '<') .']';
  $output .= ' ['. mailarchive_view_message_date($mailarchive, $message, '<') .']';
  $output .= ' ['. mailarchive_view_message_author($mailarchive, $message, '<') .']';
  $output .= '<br />';
  $output .= t('Next message: ');
  $output .= '['. mailarchive_view_message_thread($mailarchive, $message, '>') .']';
  $output .= ' ['. mailarchive_view_message_date($mailarchive, $message, '>') .']';
  $output .= ' ['. mailarchive_view_message_author($mailarchive, $message, '>') .']';
  $output .= '<br />';
  $output .= "</div>\n";
  return $output;
}

/**
 * Returns next or previous message in current thread (if any).
 */
function mailarchive_view_message_thread($mailarchive, $message, $op) {
  $sid = _mailarchive_sid($mailarchive);
  $subid = (string)rtrim((string)$message->sub_thread_id, '/');
  // Look for child message.
  if ($op == '>') {
    $new_subid = db_result(db_query("SELECT MAX(sub_thread_id) FROM {mailarchive_messages} WHERE sid = %d AND thread_id = %d AND sub_thread_id LIKE '%s.%%/'", $sid, $message->thread_id, $subid));
    if ($new_subid) {
      $message = db_fetch_object(db_query("SELECT year, month, day, mid, mailfrom, subject FROM {mailarchive_messages} WHERE sid = %d AND thread_id = %d AND sub_thread_id = '%s'", $sid, $message->thread_id, "$new_subid"));
    }
    else {
      $subids = explode('.', $subid);
      $id = sizeof($subids);
      while ($id && $subids[--$id] && !$new_mid) {
        if ($subids[$id] > 1) {
          $subids[$id] = $subids[$id] - 1;
        }
        else {
          unset($subids[$id]);
          $subids[$id - 1] = $subids[$id - 1] - 1;
        }
        $new_subid = implode('.', $subids);
        $message = db_fetch_object(db_query("SELECT year, month, day, mid, mailfrom, subject FROM {mailarchive_messages} WHERE sid = %d AND thread_id = %d AND sub_thread_id = '%s'", $sid, $message->thread_id, "$new_subid/"));
        $new_mid = $message->mid;
      }
    }
  }
  else {
    $subids = explode('.', $subid);
    $id = sizeof($subids);
    $new_mid = 0;
    while ($subids[--$id] && !$new_mid) {
      unset($subids[$id + 1]);
      $subids[$id] = $subids[$id] + 1;
      $new_subid = implode('.', $subids);
      $new_subid = db_result(db_query("SELECT MIN(sub_thread_id) FROM {mailarchive_messages} WHERE sid = %d AND thread_id = %d AND sub_thread_id LIKE '%s%%'", $sid, $message->thread_id, $new_subid));
      if ($new_subid) {
        $message = db_fetch_object(db_query("SELECT year, month, day, mid, mailfrom, subject FROM {mailarchive_messages} WHERE sid = %d AND thread_id = %d AND sub_thread_id = '%s'", $sid, $message->thread_id, $new_subid));
        $new_mid = $message->mid;
      }
      else {
        unset($subids[$id]);
        $new_subid = implode('.', $subids);
        $message = db_fetch_object(db_query("SELECT year, month, day, mid, mailfrom, subject FROM {mailarchive_messages} WHERE sid = %d AND thread_id = %d AND sub_thread_id = '%s'", $sid, $message->thread_id, "$new_subid/"));
        if (is_object($message) && $message->mid) {
          $new_mid = $message->mid;
        }
      }
    }
  }

  if (is_object($message)) {
    return l(t('thread'), "mailarchive/$mailarchive/$message->year/$message->month/$message->day/$message->mid", array('title' => "$message->mailfrom: $message->subject"));
  }
  else {
    return t('thread');
  }
}

/**
 * Returns next or previous message by date (if any).
 */
function mailarchive_view_message_date($mailarchive, $message, $op) {
  $sid = _mailarchive_sid($mailarchive);

  $today = FALSE;
  if ($op == '>') {
    $order = 'ASC';
    $year = date('Y', time());
    $month = date('n', time());
    $day = date('j', time());
    if ($message->year == $year && $message->month == $month && $message->day == $day) {
      // It is most likely to be today, so we test for this.  If it is, then
      // we know when scanning for a message later than now that we don't
      // have to scan anything other than today.
      // TODO:  Perhaps it's worth instead of checking "today" check if we're
      // in the same day as the last posting to the mailing list we're browsing.
      $today = TRUE;
    }
  }
  else {
    $order = 'DESC';
  }

  // Scan for messages today.
  $new_message = db_fetch_object(db_query("SELECT year, month, day, mid, mailfrom, subject FROM {mailarchive_messages} WHERE sid = %d AND year = %d AND month = %d AND day = %d AND received $op %d ORDER BY received $order LIMIT 1", $sid, $message->year, $message->month, $message->day, $message->received));
  if (!is_object($new_message) && !$today) {
    // Scan for messages this month.
    $new_message = db_fetch_object(db_query("SELECT year, month, day, mid, mailfrom, subject FROM {mailarchive_messages} WHERE sid = %d AND year = %d AND month = %d AND received $op %d ORDER BY received $order LIMIT 1", $sid, $message->year, $message->month, $message->received));
  }
  if (!is_object($new_message) && !$today) {
    // Scan for messages this year.
    $new_message = db_fetch_object(db_query("SELECT year, month, day, mid, mailfrom, subject FROM {mailarchive_messages} WHERE sid = %d AND year = %d AND received $op %d ORDER BY received $order LIMIT 1", $sid, $message->year, $message->received));
  }
  if (!is_object($new_message) && !$today) {
    // Full scan for messages.
    $new_message = db_fetch_object(db_query("SELECT year, month, day, mid, mailfrom, subject FROM {mailarchive_messages} WHERE sid = %d AND received $op %d ORDER BY received $order LIMIT 1", $sid, $message->received));
  }

  if (is_object($new_message)) {
    return l(t('date'), "mailarchive/$mailarchive/$new_message->year/$new_message->month/$new_message->day/$new_message->mid", array('title' => "$new_message->mailfrom: $new_message->subject"));
  }
  else {
    return t('date');
  }
}

/**
 * Returns next or previous message by author (if any).
 */
function mailarchive_view_message_author($mailarchive, $message, $op) {
  $sid = _mailarchive_sid($mailarchive);

  $today = FALSE;
  if ($op == '>') {
    $order = 'ASC';
    $year = date('Y', time());
    $month = date('n', time());
    $day = date('j', time());
    if ($message->year == $year && $message->month == $month && $message->day == $day) {
      // It is most likely to be today, so we test for this.  If it is, then
      // we know when scanning for a message later than now that we don't
      // have to scan anything other than today.
      // TODO:  Perhaps it's worth instead of checking "today" check if we're
      // in the same day as the last posting to the mailing list we're browsing.
      $today = TRUE;
    }
  }
  else {
    $order = 'DESC';
  }

  // Scan for messages today.
  $new_message = db_fetch_object(db_query("SELECT year, month, day, mid, mailfrom, subject FROM {mailarchive_messages} WHERE sid = %d AND year = %d AND month = %d AND day = %d AND mailfrom = '%s' AND received $op %d ORDER BY received $order LIMIT 1", $sid, $message->year, $message->month, $message->day, $message->mailfrom, $message->received));
  if (!is_object($new_message) && !$today) {
    // Scan for messages this month.
    $new_message = db_fetch_object(db_query("SELECT year, month, day, mid, mailfrom, subject FROM {mailarchive_messages} WHERE sid = %d AND year = %d AND month = %d AND mailfrom = '%s' AND received $op %d ORDER BY received $order LIMIT 1", $sid, $message->year, $message->month, $message->mailfrom, $message->received));
  }
  if (!is_object($new_message) && !$today) {
    // Scan for messages this year.
    $new_message = db_fetch_object(db_query("SELECT year, month, day, mid, mailfrom, subject FROM {mailarchive_messages} WHERE sid = %d AND year = %d AND mailfrom = '%s' AND received $op %d ORDER BY received $order LIMIT 1", $sid, $message->year, $message->mailfrom, $message->received));
  }
  if (!is_object($new_message) && !$today) {
    // Full scan for messages.
    $new_message = db_fetch_object(db_query("SELECT year, month, day, mid, mailfrom, subject FROM {mailarchive_messages} WHERE sid = %d AND mailfrom = '%s' AND received $op %d ORDER BY received $order LIMIT 1", $sid, $message->mailfrom, $message->received));
  }

  if (is_object($new_message)) {
    return l(t('author'), "mailarchive/$mailarchive/$new_message->year/$new_message->month/$new_message->day/$new_message->mid", array('title' => "$new_message->mailfrom: $new_message->subject"));
  }
  else {
    return t('author');
  }
}

/**
 * function to display a single message identified by message id
 *
 * @param int $messageid
 * @return string $output
 */
function theme_mailarchive_view_message ($mailarchive, $messageid) {
  $sid = _mailarchive_sid($mailarchive);
  // TODO: Optimize -- this is a performance killer.
  $message = db_fetch_object(db_query("SELECT m.mid, m.sid, m.received, m.year, m.month, m.day, m.subject, m.mailfrom, a.name, a.mailbox, a.host, a.address, m.body, m.thread_id, m.sub_thread_id FROM {mailarchive_messages} m INNER JOIN {mailarchive_messages_addresses} a ON m.mid = a.mid WHERE m.mid = '%d' AND m.sid = %d AND a.address_type = 'from'", $messageid, $sid));
  drupal_set_title($message->subject);

  if (!empty($message)) {
    $output .= '<div class="mailarchive"><div class="message-thread">';
    $output .= theme('mailarchive_view_message_nav', $mailarchive, $message);
    $output .= theme('mailarchive_view_message_header', $mailarchive, $message);
    $output .= theme('mailarchive_view_message_body', $mailarchive, $message);
    $output .= theme('mailarchive_view_message_nav', $mailarchive, $message);
    $output .= theme('mailarchive_view_message_thread_messages', $mailarchive, $message);

    // TODO: This query has awful performance, fix it then re-enable.
    //$output .= theme('mailarchive_message_footer', $mailarchive, $message);
    $output .= '</div>';
    $output .= "</div></div>\n";
  }
  else {
    drupal_goto("mailarchive/$mailarchive");
  }
 
  return $output;
}

/**
 * Outputs the message header of message including to, from, subject, and 
 * date information
 *
 * @param object $message
 * @return string $output
 */
function theme_mailarchive_view_message_header($mailarchive, $message) {
  $tos = $ccs = array();
  $result = db_query("SELECT name, mailbox, host FROM {mailarchive_messages_addresses} WHERE mid = %d AND address_type = 'to'", $message->mid);
  while ($to = db_fetch_object($result)) {
    $tos[] = "$to->name &lt;$to->mailbox@...&gt;";
  }
  $result = db_query("SELECT name, mailbox, host FROM {mailarchive_messages_addresses} WHERE mid = %d AND address_type = 'cc'", $message->mid);
  while ($cc = db_fetch_object($result)) {
    $ccs[] = "$cc->name &lt;$cc->mailbox@...&gt;";
  }

  $output = "<div class=\"message-header\">\n";
  $headers = '<div class="message-header from">';
  $headers .= t('From: !from', array('!from' => l("$message->name", "mailarchive/$mailarchive/$message->mid/search/from-name") .' &lt;'. l("$message->mailbox@...", "mailarchive/$mailarchive/$message->mid/search/from-address") .'&gt;'));
  $headers .= "</div>\n<div class=\"message-header to\">";
  if (!empty($tos)) {
    $headers .= t('To: !to', array('!to' => implode(', ', $tos)));
  }
  if (!empty($ccs)) {
    $headers .= "</div>\n<div class=\"message-header cc\">";
    $headers .= t('Cc: '. implode(', ', $ccs) .'<br/>');
  }
  $headers .= "</div>\n<div class=\"message-header subject\">";
  $headers .= t('Subject: !subject', array('!subject' => l($message->subject, "mailarchive/$mailarchive/$message->mid/search/subject")));
  $headers .= "</div>\n<div class=\"message-header date\">";
  $headers .= t('Date: @date', array('@date' => format_date($message->received, 'custom', 'l, F j, Y - g:i a')));
  $headers .= "</div>\n";
  $output .= $headers;
  $output .= "</div><br/>\n";
  return $output;
}

/**
 * Outputs the message body of the message given in $message
 *
 * @param object $message
 * @return string $output
 */
function theme_mailarchive_view_message_body($mailarchive, $message) {
  $output = "<div class=\"message-body\">\n";
  //check if the message has a body - if not, output no-message string
  if ($message->body) {
    // TODO: set this up with CSS
    $output .= '<pre>';
    $output .= htmlentities($message->body);
    $output .= '</pre>';
  }
  else {
    $output .= t('[Empty message]');
  }
  $output .= "</div>\n";
  
  return $output;
}

/**
 * outputs the threaded list of messages in the current thread (the thread containing $message)
 *
 * @param object $message
 * @return string $output
 */
function theme_mailarchive_view_message_thread_messages($mailarchive, $message) {
  $output = '<div class="current-thread"><hr />';
  $output .= '<b>'. t('Messages in current thread:') .'</b>';
	
  // List messages in this thread ordered by when received.
  $result = db_query("SELECT m.mid, m.received, m.year, m.month, m.day, m.subject, a.mailbox, a.host, a.name, m.thread_id, m.sub_thread_id FROM {mailarchive_messages} m INNER JOIN {mailarchive_messages_addresses} a ON m.mid = a.mid WHERE m.sid = %d AND m.thread_id = %d AND a.address_type = 'from' ORDER BY m.sub_thread_id DESC", $message->sid, $message->thread_id);
	   
  $i = 0;
  $output .= "<div class=\"message-list-thread\">\n";
  while($thread = db_fetch_object($result)) {
    $i++;
    if (!$thread->subject) {
      $thread->subject = t('[No subject]');
    }
    // Calculate the depth of the message.
    $message_depth = count(explode('.', $thread->sub_thread_id)) -1;
    $output .= '<div class="message-list-thread-line" style="margin-left: '. ($message_depth * 15) .'px;">';

    // Truncate fields as necessary.
    $subject = (strlen($thread->subject) > 62) ? substr(htmlspecialchars($thread->subject), 0, 60) .'...' : htmlspecialchars($thread->subject);
    $from = (strlen($thread->name) > 24) ? substr(htmlspecialchars($thread->name), 0, 60) .'...' : htmlspecialchars($thread->name);

    // If we are viewing this message, don't link it.
    if ($thread->mid == $message->mid) {
      $output .= "<span class=\"message-list-thread-subject\">$subject</span>";
    } 
    else {
      $output .= '<span class="message-list-thread-subject">'. l($subject, "mailarchive/$mailarchive/$thread->year/$thread->month/$thread->day/$thread->mid", array('title' => $thread->subject)) .'</span>';
    }
    $output .= "<span class=\"message-list-thread-from\">, $from</span>";
    $output .= '<span class="message-list-thread-date">, ('. format_date($thread->received, 'custom', 'D M j, g:i a') .")</span>";
    $output .= "</div>\n";
  }
  $output .= '</div>';

  if ($i <= 1) {
    $subscription = _mailarchive_subscription_load($message->sid);
    $output = '<div class="similar-messages"><hr />';
    $output .= t('<div class="notification">This is the only confirmed message in this thread.</div>');
    $subjects = _mailarchive_view_get_subjects($message->sid, $message->mid);
    $result = _mailarchive_view_search_subjects($message->sid, $subjects, 15);
    $i = 0;
    // Build list of all messages.
    $items = array();
    while ($current = db_fetch_object($result)) {
      $i++;
      $subject = $current->mid == $message->mid ? $current->subject : l($current->subject, "mailarchive/$subscription->urlname/$current->year/$current->month/$current->day/$current->mid");
      $items[] = $subject .' by '. l($message->mailfrom, "mailarchive/$subscription->urlname/$current->mid/search/from-name") .' on '. format_date($current->received, 'custom', 'M j, g:i a Y');
    }
    if ($i > 1) {
      $output .= '<b>'. t('Possibly related messages:') .'</b>';
      $output .= theme('item_list', $items);
      $output .= theme('pager', 15);
    }
  }

  return $output;
}

/**
 * Provides links to the next and previous threads in the current archive
 *
 * @param object $message
 * @return string $output
 */
function theme_mailarchive_view_message_footer($mailarchive, $message) {
  $output = '<div class="message-footer" >';
  $output .= '<hr/>';

  // Find the message ids of the previous and next messages.
  $prev = db_fetch_object(db_query("SELECT mid, subject FROM mailarchive_messages WHERE sub_thread_id = '1/' AND thread_id IN ( SELECT MAX(thread_id) AS thread_id FROM mailarchive_messages WHERE sid = %d AND thread_id < %d)", $message->sid, $message->thread_id));
  $next = db_fetch_object(db_query("SELECT mid, subject FROM mailarchive_messages WHERE sub_thread_id = '1/' AND thread_id IN ( SELECT MIN(thread_id) AS thread_id FROM mailarchive_messages WHERE sid = %d AND thread_id > %d)", $message->sid, $message->thread_id));

  // Output the links to the next and previous messages if there are next and 
  // previous messages if one of them doesn't exist, then just use the text 
  // with no link.
  // TODO: Replace table with CSS.
  $output .= "<div align='center'><table border=0><tr><td width=150 align='right'>";
  if($prev->mid) {
    $output .= l('< Previous Thread', "mailarchive/$mailarchive/$prev->mid", array('title' => $prev->subject));
  } 
  else {
    $output .= "< Previous Thread";	
  }
  $output .= "</td><td width=40></td><td width=150 align='left'>";
  if($next->mid) {
    $output .= l('Next Thread >',"mailarchive/$mailarchive/$next->mid", array('title' => $next->subject));
  } 
  else {
    $output .= "Next Thread >";
  }
  $output .= "</td></tr></table>";
	
  $output .= '</div>';
  return $output;
}

/**
 * Returns a list of all messages with the same (or a similar) subject as the
 * passed in message.
 */
function mailarchive_view_search_subject($sid, $mid) {
  $subscription = _mailarchive_subscription_load($sid);
  // Set breadcrumbs and page title.
  $subjects = _mailarchive_view_get_subjects($sid, $mid);
  drupal_set_title(t('Messages in %subscription with subject: %subject', array('%subscription' => $subscription->urlname, '%subject' => $subjects[0]))); 
  _mailarchive_view_set_breadcrumb($sid, $mid);
  $result = _mailarchive_view_search_subjects($sid, $subjects, 25);
  // Build list of all messages.
  $items = array();
  while ($message = db_fetch_object($result)) {
    $items[] = l($message->subject, "mailarchive/$subscription->urlname/$message->year/$message->month/$message->day/$message->mid"). ' by '. l($message->mailfrom, "mailarchive/$subscription->urlname/$message->mid/search/from-name") .' on '. format_date($message->received, 'custom', 'M j, g:i a Y');
  }
  $output = '<div class="mailarchive"><div class="search-subject">';
  $output .= theme('item_list', $items);
  $output .= theme('pager', 25);
  $output .= "</div></div>\n";
  return $output;
}

/**
 * Returns a list of all messages with the same from name as the passed in
 * message.
 */
function mailarchive_view_search_from_name($sid, $mid) {
  $subscription = _mailarchive_subscription_load($sid);
  // Set breadcrumbs and page title.
  $name = db_result(db_query("SELECT name FROM {mailarchive_messages_addresses} WHERE mid = %d AND address_type = 'from' AND sid = %d", $mid, $sid));
  drupal_set_title(t('Messages in %subscription from: %name', array('%subscription' => $subscription->urlname, '%name' => $name))); 
  _mailarchive_view_set_breadcrumb($sid, $mid);
  // Display list of messages by name.
  $result = pager_query("SELECT subject, received, year, month, day, mid, mailfrom FROM mailarchive_messages WHERE mailfrom = '". addslashes($name) ."' AND sid = $sid ORDER BY received DESC", 25);
  $items = array();
  while ($message = db_fetch_object($result)) {
    $items[] = l($message->subject, "mailarchive/$subscription->urlname/$message->year/$message->month/$message->day/$message->mid"). " by $message->mailfrom on ". format_date($message->received, 'custom', 'M j, g:i a Y');
  }
  $output = '<div class="mailarchive"><div class="search-subject">';
  $output .= theme('item_list', $items);
  $output .= theme('pager', 25);
  $output .= "</div></div>\n";
  return $output;
}

/**
 * Returns a list of all messages with the same from address as the passed in
 * message.
 */
function mailarchive_view_search_from_address($sid, $mid) {
  $subscription = _mailarchive_subscription_load($sid);
  // Set breadcrumbs and page title.
  $from = db_fetch_object(db_query("SELECT mailbox, address FROM {mailarchive_messages_addresses} WHERE mid = %d AND address_type = 'from' AND sid = %d", $mid, $sid));
  drupal_set_title(t('Messages in %subscription from: %address (domain blocked)', array('%subscription' => $subscription->urlname, '%address' => $from->mailbox .'@...'))); 
  _mailarchive_view_set_breadcrumb($sid, $mid);
  // list of messages by from address.
  $sql = "SELECT m.mid, m.subject, m.received, m.year, m.month, m.day, a.name, a.mailbox FROM {mailarchive_messages_addresses} a JOIN {mailarchive_messages} m ON a.mid = m.mid WHERE address = '". addslashes($from->address) ."' AND address_type = 'from' AND m.sid = $sid ORDER BY m.received DESC";
  $result = pager_query($sql, 25);
  $items = array();
  while ($message = db_fetch_object($result)) {
    if ($message->name) {
      $from = $message->name;
    }
    else {
      $from = $message->mailbox;
    }
    $items[] = l($message->subject, "mailarchive/$subscription->urlname/$message->year/$message->month/$message->day/$message->mid"). " by $from on ". format_date($message->received, 'custom', 'M j, g:i a Y');
  }
  $output = '<div class="mailarchive"><div class="search-subject">';
  $output .= theme('item_list', $items);
  $output .= theme('pager', 25);
  $output .= "</div></div>\n";
  return $output;
}

/**
 * Helper function to simplify setting the breadcrumb on mailarchive pages.
 */
function _mailarchive_view_set_breadcrumb($sid, $mid = NULL, $year = NULL, $month = NULL, $day = NULL) {
  $breadcrumb = array(l(t('Home'), NULL), l(t('Mailing list archives'), 'mailarchive'));
  if ($mid) {
    $subscription = _mailarchive_subscription_load($sid);
    $breadcrumb[] = l(t($subscription->urlname), "mailarchive/$subscription->urlname");
  }
  if ($year) {
    $breadcrumb[] = l($year, "mailarchive/$subscription->urlname/$year");
  }
  if ($month) {
    $breadcrumb[] = l(mailarchive_view_format_month($month), "mailarchive/$subscription->urlname/$year/$month");
  }
  if ($day) {
    $breadcrumb[] = l($day, "mailarchive/$subscription->urlname/$year/$month/$day");
  }
  drupal_set_breadcrumb($breadcrumb);
}

/**
 * Return an array of subjects extracted from the current message.
 */
function _mailarchive_view_get_subjects($sid, $mid) {
  $subjects = array();
  $subjects[] = db_result(db_query('SELECT subject FROM {mailarchive_messages} WHERE sid = %d and mid = %d', $sid, $mid));
  // Remove common prefixes from subject.
  $subjects[0] = ltrim(preg_replace('/^(re:)||^(fw:)/i', '', $subjects[0]));

  // Extract (was: ...) or [was: ...] style previous subjects.
  preg_match('&(.*)(\[)?(\()?was:( *)(.*)(\])?(\))?&i', $subjects[0], $match);
  if (isset($match[5])) {
    $subjects[] = trim(preg_replace('/^(re:)||^(fw:)/i', '', $match[5]), ' \t\n\r\0)]');
  }
  if (isset($match[1])) {
    $subjects[] = trim(preg_replace('/^(re:)||^(fw:)/i', '', $match[1]), ' \t\n\r\0([');
  }

  // Extract (re: ...) or [re: ...] style previous subjects.
  preg_match('&(.*)(\[)?(\()?re:( *)(.*)(\])?(\))?&i', $subjects[0], $match);
  if (isset($match[5])) {
    $subjects[] = trim(preg_replace('/^(re:)||^(fw:)/i', '', $match[5]), ' \t\n\r\0)]');
  }
  if (isset($match[1])) {
    $subjects[] = trim(preg_replace('/^(re:)||^(fw:)/i', '', $match[1]), ' \t\n\r\0)]');
  }

  return $subjects;
}

function _mailarchive_view_search_subjects($sid, $subjects, $limit = 10) {
  $filter = '';
  foreach ($subjects as $subject) {
    if ($filter) {
      $filter .= " OR subject LIKE '%%". db_escape_string($subject) ."%%'";
    }
    else {
      $filter = " AND (subject LIKE '%%". db_escape_string($subject) ."%%'";
    }
  }
  $filter .= ')';
  return pager_query("SELECT mid, subject, received, year, month, day, mailfrom FROM {mailarchive_messages} WHERE sid = $sid $filter ORDER BY received DESC", $limit);
}

// TODO: This function is unused.
function theme_mailarchive_view_content($node, $teaser=FALSE) {
  //$output = "<div class=\"mailarchive\" id=\"mailarchive-$node->lid\">\n";
  $output = "<div class=\"mailarchive\">\n";
  $output .= $node->body;
  if ($node->messages) {
    $output .= '<p>'. l(t('%messages messages.', array('%messages' => $node->messages)), "mailarchive/$node->lid/overview/thread"). '  '. t('The last message was posted %time ago.', array('%time' => format_interval(time() - $node->last))) .'</p>';
  }
  else {
    $output .= '<p>'. t('There have been no messages posted to this mailing list.') .'</p>';
  }
  $output .= "</div>\n";

  $node->body = $output;
  $node = node_prepare($node, $teaser);
}

